# Generated by Django 5.2.1 on 2025-05-21 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 20, 42, 15, 656720, tzinfo=datetime.timezone.utc)),
        ),
    ]
