# Generated by Django 5.2.1 on 2025-05-22 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 22, 1, 45, 1, 699282, tzinfo=datetime.timezone.utc)),
        ),
    ]
