# Generated by Django 5.2.1 on 2025-05-15 20:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, unique=True)),
                ('species', models.IntegerField(choices=[(1, 'Cattle'), (2, 'Poultry'), (3, 'Pig'), (4, 'Sheep'), (5, 'Goat'), (99, 'Other')], default=99)),
                ('purchase_date', models.DateField()),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Mixed')], default=3)),
                ('quantity', models.PositiveIntegerField()),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=100, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('health_status', models.IntegerField(choices=[(1, 'Healthy'), (2, 'Sick'), (3, 'Recovering'), (4, 'Dead')], default=1)),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Mixed')], editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farm.animalbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FEED', 'Alimento'), ('VET', 'Veterinaria'), ('MAINTENANCE', 'Mantenimiento'), ('LABOR', 'Mano de obra'), ('EQUIPMENT', 'Equipamiento'), ('OTHER', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('€', 'Euros'), ('$', 'Dollars'), ('', 'Other')], default='€', max_length=5)),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('BANK_TRANSFER', 'Transferencia Bancaria'), ('MOBILE_PAYMENT', 'Pago Móvil'), ('CHECK', 'Cheque'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='farm.animalbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('illness', 'Illness'), ('treatment', 'Treatment'), ('checkup', 'Checkup'), ('vaccine', 'Vaccine'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('veterinarian', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='farm.animal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SALE', 'Venta'), ('SUBSIDY', 'Subvención'), ('DONATION', 'Donación'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('€', 'Euros'), ('$', 'Dollars'), ('', 'Other')], default='€', max_length=5)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='farm.animalbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('MEAT', 'Carne'), ('MILK', 'Leche'), ('EGG', 'Huevos'), ('WOOL', 'Lana')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit', models.CharField(choices=[('L', 'Litros'), ('KG', 'Kilogramos'), ('U', 'Unidades')], max_length=2)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='farm.animalbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
