# Generated by Django 5.2.1 on 2025-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FEED', 'Feed'), ('VET', 'Veterinary'), ('MAINTENANCE', 'Maintenance'), ('LABOR', 'Labor'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_PAYMENT', 'Mobile Payment'), ('CHECK', 'Check'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SUBSIDY', 'Subsidy'), ('DONATION', 'Donation'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
