# Generated by Django 5.2.1 on 2025-05-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_expense_category_alter_expense_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='production_type',
            field=models.CharField(choices=[('MEAT', 'Meat'), ('MILK', 'Milk'), ('EGG', 'Eggs'), ('WOOL', 'Wool')], max_length=10),
        ),
        migrations.AlterField(
            model_name='production',
            name='unit',
            field=models.CharField(choices=[('L', 'Liters'), ('KG', 'Kilograms'), ('U', 'Units')], max_length=2),
        ),
    ]
